name: Heimdall CI

on: push

jobs:
  # Only works for pushes, not pull_requests
  prepare:
    name: Prepare

    runs-on: ubuntu-latest

    if: "! contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:
    name: Build

    runs-on: ubuntu-latest

    needs: prepare

    steps:
    - uses: actions/checkout@v2

    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.10.4'
        otp-version: '22.3'

    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Compilation
      run: mix compile

  mix-test:
    name: Mix Test

    runs-on: ubuntu-latest

    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.10.4'
        otp-version: '22.3'

    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Run tests
      run: mix test

  mix-sobelow:
    name: Mix Sobelow

    runs-on: ubuntu-latest

    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.10.4'
        otp-version: '22.3'

    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Run sobelow
      run: |
        cd apps/bifrost
        mix sobelow

  coverage:
    name: Mix Coverage

    runs-on: ubuntu-latest

    needs: build

    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.10.3'
        otp-version: '22.3'

    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Run Coverage
      run: mix coveralls

    - name: Report Coverage
      run: mix coveralls.github

  elixir_fmt:
    name: Mix Format

    runs-on: ubuntu-latest

    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.10.3'
        otp-version: '22.3'

    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Check formatted
      run: mix format --check-formatted

  js_fmt:
    name: JS Beautify Format

    runs-on: ubuntu-latest

    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 11.15.0

    - name: Install npm formatter
      run: npm install -g js-beautify

    - name: Check formatted
      run: |
        cd browser-tests/cypress/integration/
        js-beautify -r *.js
        git diff --exit-code .

  browser-test:
    name: Browser Test

    runs-on: ubuntu-latest

    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.10.3'
        otp-version: '22.3'

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 11.15.0

    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Install npm deps
      run: cd apps/bifrost/assets && npm install

    - name: Install cypress dependencies
      run: |
        cd browser-tests && npm install cypress --save-dev && npm install

    - name: Run phoenix server & browser tests
      env:
        BIFROST_PORT: 4010
        BIFROST_USER: dev_user
        BIFROST_PASSWORD: secret
        CYPRESS_BIFROST_PORT: 4010
        CYPRESS_BIFROST_USER: dev_user
        CYPRESS_BIFROST_PASSWORD: secret

      run: ./browser-test-runner.sh
